### ISSUE TITLE
[f01] corrections

### ISSUE THREAD

**Issue by Kossyr** [Kossyr/dawn#165]
Small corrections based on feedback

**Comment by SmausJakub** [comment]
Hurrah sounds make with different voices and different dynamics. It sounded like clones - not way to go.
21:21 why is he angry? Only for consideration, already discussed.
49:21 maybe a bit odd logic from Zubarev but was intentional, just want to give all my notes prepared from meeting.

**Comment by Kossyr** [comment]
> 19 x < 37

**Comment by Kossyr** [comment]
Any issue with the sound shall be left for beta version
